plugins:
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton

skin: daylight

title: kirkkohler.com
site-title: Kirk Kohler
author: Kirk Kohler
avatar: https://pbs.twimg.com/profile_images/539674730848989184/rK1Tijv__400x400.jpeg
google_analytics: UA-34904642-1
